FROM docker.io/cimg/android:2021.09.1-ndk AS build

RUN \
	export DEBIAN_FRONTEND=noninteractive && \
	sudo apt update && \
	sudo apt install -y fpc gdb zip

COPY fpcbuild-*.tar.gz *.patch *.sh /scripts/
RUN \
	mkdir ~/build && \
	/scripts/build-fpc.sh --install user ~/build 3.2.2

ARG ANDROID_API
ENV ANDROID_API=${ANDROID_API:-21}

RUN \
	/scripts/build-fpcross.sh --install user ~/build 3.2.2 aarch64 && \
	/scripts/build-fpcross.sh --install user ~/build 3.2.2 arm && \
	/scripts/build-fpcross.sh --install user ~/build 3.2.2 x86_64

# -- Phase 2
# Start with a clean container

FROM docker.io/cimg/android:2021.09.1-ndk

COPY --from=build /home/circleci/fpc /home/circleci/fpc
ENV PATH="/home/circleci/fpc/bin:${PATH}"

ARG ANDROID_API
ENV ANDROID_API=${ANDROID_API:-21}

# - binutils: not needed for Android, but required by fpc for linking native executables
# - file: used by ndk-build (though not strictly *required*)
# - make: required by ndk-build
RUN \
	export DEBIAN_FRONTEND=noninteractive && \
	sudo apt update && \
	sudo apt install -y binutils file make && \
	sudo apt clean

